import Head from "next/head";
import { Inter } from "@next/font/google";
import Home from "../src/components/Home";

const inter = Inter({ subsets: ["latin"] });

export default function HomePage({ data }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home data={data} />
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
