import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img src="" alt="" />
          <a href="/">Accueil</a>
          <a href="/events">Évènements</a>
          <a href="/about">À propos</a>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((elem) => (
          <a key={elem.id} href={`/events/${elem.id}`}>
            <Image src={elem.image} alt={elem.title} width={200} height={200} />
            <h2>{elem.title}</h2>
            <p>{elem.description}</p>
          </a>
        ))}
      </main>

      <footer className={styles.footer}>
        <p>
          &#169; 2023 Maxime Quagebeur - Prictice Project Built With Next.js
        </p>
      </footer>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
